version: "3.9"

services:
  node-app:
    build: ./node
    ports:
      - "3000:3000"

  python-app:
    build: ./python
    ports:
      - "5000:5000"

  java-app:
    build: ./java
    ports:
      - "8080:8080"

