services:
  java-app:
    image: bandarudocker/my_repo_docker:java-${IMAGE_TAG}
    ports:
      - "8080:8080"

  node-app:
    image: bandarudocker/my_repo_docker:node-${IMAGE_TAG}
    ports:
      - "3000:3000"

  python-app:
    image: bandarudocker/my_repo_docker:python-${IMAGE_TAG}
    ports:
      - "5000:5000"

