name: CI/CD Docker Compose Deployment

on:
  push:
    branches:
      - main
env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Java Image
        uses: docker/build-push-action@v5
        with:
          context: ./java
          push: true
          tags: |
                bandarudocker/my_repo_docker:java
                bandarudocker/my_repo_docker:java-${{ env.IMAGE_TAG }}

      - name: Build & Push Node Image
        uses: docker/build-push-action@v5
        with:
          context: ./node
          push: true
          tags: |
                bandarudocker/my_repo_docker:node
                bandarudocker/my_repo_docker:node-${{ env.IMAGE_TAG }}
      - name: Build & Push Python Image
        uses: docker/build-push-action@v5
        with:
          context: ./python
          push: true
          tags: |
                bandarudocker/my_repo_docker:python
                bandarudocker/my_repo_docker:python-${{ env.IMAGE_TAG }}
      - name: Deploy to Azure VM
        run: |
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

              ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
              cd ~/my-practice
              export IMAGE_TAG=${{ github.sha }}
              docker compose pull
              docker compose down
              docker compose up -d
              EOF

